export const discordManageTools = [
  {
        name: "discord_manage",
        description:
          "Comprehensive Discord server management tool - handles all Discord operations through a single unified interface",
        inputSchema: {
          type: "object",
          properties: {
            action: {
              type: "string",
              enum: [
                "get_server_info",
                "send_message",
                "reply_message",
                "edit_message",
                "delete_message",
                "read_messages",
                "pin_message",
                "unpin_message",
                "get_pinned_messages",
                "bulk_delete_messages",
                "crosspost_message",
                "get_message_history",
                "get_message_attachments",
                "read_images",
                "get_user_id_by_name",
                "send_private_message",
                "edit_private_message",
                "delete_private_message",
                "read_private_messages",
                "add_reaction",
                "remove_reaction",
                "create_text_channel",
                "create_voice_channel",
                "create_forum_channel",
                "create_announcement_channel",
                "create_stage_channel",
                "edit_channel_advanced",
                "delete_channel",
                "find_channel",
                "list_channels",
                "set_channel_position",
                "set_channel_positions",
                "move_channel_to_category",
                "organize_channels",
                "get_channel_structure",
                "create_category",
                "delete_category",
                "find_category",
                "list_channels_in_category",
                "set_category_position",
                "create_webhook",
                "delete_webhook",
                "list_webhooks",
                "send_webhook_message",
                "join_voice_channel",
                "leave_voice_channel",
                "play_audio",
                "stop_audio",
                "set_volume",
                "get_voice_connections",
                "create_role",
                "delete_role",
                "edit_role",
                "add_role_to_member",
                "remove_role_from_member",
                "get_roles",
                "set_role_positions",
                "get_members",
                "search_members",
                "edit_member",
                "get_member_info",
                "create_event",
                "edit_event",
                "delete_event",
                "get_events",
                "create_invite",
                "delete_invite",
                "get_invites",
                "create_emoji",
                "delete_emoji",
                "get_emojis",
                "create_sticker",
                "delete_sticker",
                "get_stickers",
                "upload_file",
                "set_channel_private",
                "set_category_private",
                "bulk_set_privacy",
                "comprehensive_channel_management",
                "create_automod_rule",
                "edit_automod_rule",
                "delete_automod_rule",
                "get_automod_rules",
                "send_modal",
                "send_embed",
                "send_button",
                "send_select_menu",
                "edit_server",
                "get_server_widget",
                "get_welcome_screen",
                "edit_welcome_screen",
                "get_server_stats",
                "export_chat_log",
              ],
              description: "The specific Discord operation to perform",
            },
          },
          required: ["action"],
          additionalProperties: true,
        },
      }
];
